### ISSUE TITLE
Should `output` be checked in?

### ISSUE THREAD

**Issue by cmoesel** [Healthedata1/barebones-fhir-ig#1]
I noticed that the `output` folder is checked in with all of the built artifacts that were generated by a run of the IG publisher.  Did you intentionally check in `output` and all of the build artifacts?

**Comment by Healthedata1** [comment]
yes since this is not an autobuild and reasonably small I just load it to
Git Hub pages directly.   I prefer to share the draft output this  quick
and dirty way so I don't fight with the autobuilder.


Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, CA 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by cmoesel** [comment]
Got it.  And it makes sense.  Thanks for the info.
